spring:
  datasource:
    url: jdbc:mysql://localhost:3306/computermall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: wcy011230
    driver-class-name: com.mysql.jdbc.Driver
    favicon:
      enabled: off
  servlet:
    multipart:
      max-request-size: 1GB  # 上传文件总的最大值 默认10MB
      max-file-size: 10MB #单个文件最大值 默认10MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: is_delete
      logic-not-delete-value: 0
      logic-delete-value: 1
user:
  address:
    max-count: 20
